;===========================================================
; ESP32 Smart Radio V2
;===========================================================

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_build.partitions = default_8MB.csv

board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

monitor_speed = 115200


lib_ignore =
    RPAsyncTCP
    ESPAsyncTCP

lib_deps =
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    esphome/ESP32-audioI2S
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    bodmer/TJpg_Decoder
    HTTPClient
    WiFiClientSecure


build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Isrc