;===========================================================
; ESP32 Smart Radio V2
;===========================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv

monitor_speed = 115200
upload_speed = 921600

lib_ignore =
    RPAsyncTCP
    ESPAsyncTCP

lib_deps =
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    HTTPClient
    WiFiClientSecure
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Isrc